### ISSUE TITLE
compiling fails

### ISSUE THREAD

**Issue by tolgamyth** [AlekSi/breakpad-qt#1]
breakpad-qt-master/third-party/google-breakpad/src/client/linux/handler/minidump_generator.cc:182: error: 'const struct sigcontext' has no member named 'ebx'
   context->ebx = sig_ctx->ebx;
                           ^

sigcontext really has no member ebx how could you compiled it successfully?(mine on linux)

**Comment by AlekSi** [comment]
This repository is no longer maintained.

**Comment by AlekSi** [comment]
But can try to apply patch: https://github.com/AlekSi/breakpad-qt/tree/master/third-party
